name: InfluxDB3 Explorer
version: 0.1.2
slug: influxdb3-explorer
description: InfluxDB3 Explorer for Home Assistant
url: https://github.com/jimmyhideous/app-influxdb3-explorer
init: false
arch:
- aarch64
- amd64
ingress: true
ingress_port: 80
panel_icon: mdi:database
panel_title: InfluxDB3 Explorer
ports:
  80/tcp: 8888
ports_description:
  80/tcp: InfluxDB3 Explorer
options:
  log_level: info
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)
image: ghcr.io/jimmyhideous/app-influxdb3-explorer/{arch}
