---
name: Deploy to Github Pages

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - master

permissions: {}

jobs:
  deploy:
    name: Deploy docs to GitHub Pages
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@v4.3.1

      - name: Set up Python
        uses: actions/setup-python@v5.3.0
        with:
          python-version: '3.12'

      - name: Upgrade pip
        run: python3 -m pip install --upgrade pip

      - name: Get pip cache dir
        id: pip-cache
        run: echo "dir=$(pip cache dir)" >> "$GITHUB_OUTPUT"

      - name: Cache dependencies
        uses: actions/cache@v4.1.2
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: python3 -m pip install -r ./requirements.txt

      - name: Build docs
        run: |
          mkdir -p docs
          ln -sf ../README.md docs/index.md
          ln -sf ../LICENSE.md docs/LICENSE.md
          ln -sf ../CONTRIBUTING.md docs/contributing.md
          ln -sf ../CODE_OF_CONDUCT.md docs/code-of-conduct.md
          mkdocs build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./site
          keep_files: true
